### PR TITLE
Add vectorised implementations

### PR DESCRIPTION
**Pull request by jeromekelleher**
Turns out you make this *much* faster by doing multiple sites at a time (learning lessons from the R implementation)

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Here's some updated plots:

tree-performance-sequential

This is the updated sequential version. New here is Biopython, which I think we need to include to give a sense of how *much* slower these pure Python versions are. I had to remote the C++ versions as they ran out of memory on my machine (will follow up with an issue)

**Comment by jeromekelleher** [comment]
Here are the vectorised versions

tree-performance-vectorised

Basically the C version is fastest, but pretty close to numba when we don't fix align our memory layout with the node ordering. The C version could probably be made faster if we looking at using vector instructions, but I'm not sure it's worth the bother.

Numba is *faster than phangorn* despite it being written in C! (I think it's done somewhere in [here](https://github.com/KlausVigo/phangorn/blob/309d79be14d2a5bf62b5f0247efd2bfcbe65cfdc/src/sankoff.c#L89))

**Comment by jeromekelleher** [comment]
And these are the close-to-the-metal relative values:


tree-performance-relative

It is quite a lot faster to do lots of sites at once. This probably isn't a very good way of displaying the information, though.

**Comment by molpopgen** [comment]
Odd the c++ versions ran out of memory.  How much is on your machine?  The solution is probably to do each one separately, so that main isn't holding all 3 at once.

**Comment by jeromekelleher** [comment]
Opened an issue in #18 @molpopgen

**Pull request merged**
