### PR TITLE
fix cpp tree building

### PR DESCRIPTION
**Pull request by molpopgen**
Fixes the cpp tree builder to work with msprime order and preorder input data.

### CODE REVIEW

**Comment by molpopgen** [comment]
@jeromekelleher -- there's some cleanup to do before merging.

**Review by jeromekelleher — COMMENTED** [review]
LGTM, are we good to merge @molpopgen?

**Comment by molpopgen** [comment]
Yeah, good to merge.  I still don't have merge privileges.

There are a few things where one could replace the use of the raw pointer w/access into the C++ vector, but the machine code is all going to be the same (vector just holds a T*, etc..).

**Comment by jeromekelleher** [comment]
Merged - you should have merge access now? (I created a new team)

**Pull request merged**
